### ISSUE TITLE
new_green_cars_train.pkl and _new_green_cars_test.pkl_ missing

### ISSUE THREAD

**Issue by ehsanul9511** [ksreenivasan/OOD_Federated_Learning#7]
In utils.py line 719 and 722, two dataset files are mentioned: _new_green_cars_train.pkl_ and _new_green_cars_test.pkl_. But they are not available in the repo. I am assuming they are related to the semantic backdoor attack. In any case, is it possible to share these files?

Thanks,
Ehsanul

**Comment by ksreenivasan** [comment]
Hi @ehsanul9511,

I think the green car experiment was one that we tried early on but didn't decide to use in the final paper. We just stuck to the airlines example. Unfortunately, I can't seem to track it down but if I remember correctly we constructed it by simply scraping some green car images from a Google search and downsampling it to 32x32 so that it aligns with CIFAR-10. But for the purposes of your experiment, you might just be able to directly use the green cars in CIFAR-10 which you can find using this [line of code](https://github.com/ksreenivasan/OOD_Federated_Learning/blob/master/utils.py#L217)

**Comment by ehsanul9511** [comment]
Thank you, @ksreenivasan, for your prompt response. I am running semantic backdoor attack and these two files directly fit into what I need based on what you mentioned. But it's perfectly alright, now that you mentioned the way you collected these images, I am planning to do the same. The green car indices in CIFAR-10 were particularly helpful as well, many thanks for those.

**Comment by ksreenivasan** [comment]
You're welcome @ehsanul9511! All the best for your experiments! Happy to chat more.
